version: 2.1
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: dev
jobs:
  build:
    docker:
      - image: 'circleci/openjdk:8-jdk'
        environment:
          MULE_APP_NAME: demo-lfsv-hellow-app
          MULE_ENV: Sandbox
          MULE_WORKER_TYP: Micro
          MULE_WORKER: 1
          MULE_REGION: us-east-2
          MULE_OSv2: true
    steps:
      - run:
          name: Test
          command: |
            mvn clean compile 
      