version: 2.1
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: dev
jobs:
  build:
    docker:
      - image: 'circleci/openjdk:8-jdk'
        environment:
          MULE_APP_NAME: demo-lfsv-hellow-app
          MULE_ENV: Sandbox
          MULE_WORKER_TYP: Micro
          MULE_WORKER: 1
          MULE_REGION: us-east-2
          MULE_OSv2: true
    steps:
      - run:
          name: Test
          command: |
            curl https://maven.anypoint.mulesoft.com/api/v3/maven/34e5fc2b-f957-4909-9eea-958a2f9af657/sys-salesforce-api/1.0.0/sys-salesforce-api-1.0.0.pom
      